### ISSUE TITLE
IKK todo for launch

### ISSUE THREAD

**Issue by bradallenfisher** [bradallenfisher/fws#3]
- [ ] tag sticky recipes
- [ ] move recipes into proper categories.
- [ ] add popular recips block to home page
- [ ] sort recipes by popularity in all recipes page.
